### PR TITLE
Modify builder files

### PR DESCRIPTION
**Pull request by johnReeve**
I wasn't finding a place to add a CPT, so I added a workflow for doing that.  Basically, I moved the buildfile list to the config and have Plugin:build() loop through that... so you can add CPTs there, or maybe some other global-level registration file?

I dunno-- I can see why that might not be a great direction, but it's my initial impulse.

### CODE REVIEW

**Comment by jasonagnew** [comment]
Thanks for this. I like your idea of having a way to include any file. I’ll look to integrate this on Friday. Just want to take some time to think over it.

**Comment by johnReeve** [comment]
No hurry... like I said, it's maybe not the best way of doing it.

**Comment by ConnorVG** [comment]
Hey John, there is currently a much nicer way of doing this now. Thanks for bringing this to light! :-)

Hopefully I'll get this version done ASAP.

**Comment by jasonagnew** [comment]
Thanks, we've addressed this in the new version.

**Pull request closed without merging**
